import { ConverterCard } from "@/features/converter";
import { MainHeader } from "@/features/header";
import { HeadingCtx } from "@/shared/heading";
import { ThemeSwitch } from "@/shared/theme";
import { Navbar } from "@/shared/utils";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <HeadingCtx value={0}>
          <MainHeader>
            <ThemeSwitch />
          </MainHeader>
          <ConverterCard />
          <Navbar />
          {children}
        </HeadingCtx>
      </body>
    </html>
  );
}
