import { AuthManager } from "@/features/account";
import { ConverterCard } from "@/features/converter";
import { MainHeader } from "@/features/header";
import { HeadingCtx, Main } from "@/shared/heading";
import { ThemeSwitch } from "@/shared/theme";
import { Navbar } from "@/shared/utils";
import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jetBrains = JetBrains_Mono({
  variable: "--font-jet-brains-mono",
  subsets: ["latin"],
  weight: ["600", "400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${jetBrains.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <HeadingCtx value={0}>
          <Main pageHasH1={false}>
            <MainHeader>
              <ThemeSwitch />
              <AuthManager />
            </MainHeader>
            <div className="max-w-4xl mx-auto sm:py-8">
              <ConverterCard />
              <Navbar history={{}} compare={{}} favorites={{}} logs={{}} />
              {children}
            </div>
          </Main>
        </HeadingCtx>
      </body>
    </html>
  );
}
